environment: production
chdir: /usr/local/apps/quick_label
address: 127.0.0.1
#user: www
#group: www
port: 4567
pid: /usr/local/apps/quick_label/thin.pid
rackup: /usr/local/apps/quick_label/config.ru
log: /usr/local/apps/quick_label/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
