environment: production
chdir: /usr/local/apps/quick_barcode
address: 127.0.0.1
#user: www
#group: www
port: 4568
pid: /usr/local/apps/quick_barcode/thin.pid
rackup: /usr/local/apps/quick_barcode/config.ru
log: /usr/local/apps/quick_barcode/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
