environment: production
chdir: /usr/local/apps/eisai-label
address: 127.0.0.1
#user: www
#group: www
port: 4569
pid: /usr/local/apps/eisai-label/thin.pid
rackup: /usr/local/apps/eisai-label/config.ru
log: /usr/local/apps/eisai-label/thin.log
max_conns: 1024
timeout: 30
max_persistent_conns: 512
daemonize: true
